services:
  jekyll:
    image: jekyll/jekyll:4
    platform: linux/amd64
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll
    command: >
      jekyll serve
      --watch
      --force_polling
      --host 0.0.0.0
